Repository SRINIDHI-G/peasmane, pull requests merged in 2021-10, with the labels that each got.

#4 okay
  oka
Labels: hacktoberfest-accepted

#5 ing roshthida
  oka
Labels: enhancement, hacktoberfest-accepted

#6 okay
  oka
Labels: enhancement, hacktoberfest-accepted

#7 welcome
  oka
Labels: good first issue, hacktoberfest-accepted

#8 ok
  oka
Labels: hacktoberfest-accepted

#9 okay mane
  oka
Labels: hacktoberfest-accepted

#10 okay done mane
  oka
Labels: hacktoberfest-accepted

#11 done mane ?
  oka
Labels: hacktoberfest-accepted

#12 pok
  oka
Labels: hacktoberfest-accepted

#13 o
  oka
Labels: hacktoberfest-accepted

#15 ok
  oka
Labels: hacktoberfest-accepted

#16 okok
  oka
Labels: hacktoberfest-accepted

#19 mann
  oka
Labels: hacktoberfest-accepted

#22 update ok
  oka
Labels: hacktoberfest-accepted

#24 updated
  oka
Labels: hacktoberfest-accepted
